name: Hello World Workflow
on: [push] # This workflow runs on every push to the repository

jobs:
  build:
    runs-on: ubuntu-latest # Specifies the operating system for the job
    permissions:
      contents: read
      pull-requests: write
    steps:
    - name: Print Hello World
      run: echo "Hello World!" # Executes the command to print "Hello World!"
